#!/bin/bash

usage(){
    echo "Usage: ./analyzer -f file.drisc -s n"
    exit
}

if [ "$#" -eq 0 -o "$#" -eq 1 -o "${2##*.}" != "drisc"  ]; then
    usage
fi

while getopts ":f:s:" opt; do
  case ${opt} in
    f ) f=$OPTARG
      ;;
    s ) n=$OPTARG
      ;;
    \? ) usage
      ;;
  esac
done
shift $((OPTIND -1))

if [ -z "${f}" ] || [ -z "${n}" ]; then
    usage
fi

./dep ${f} ${n} < ${f}
