/**
 * @file parse_util.h
 * @author Chiara Caglieri
 * @brief Header containing
 *        utility functions for the analyzer
 */
#include <unordered_map>
#include <deque>
#include <string>
#include <vector>
#include <fstream>

using namespace std;

struct node{
    string type;         /**<Type of node */
    int value;           /**<Numerical value for VALUE-type nodes */
    int pc;              /**<Program Counter */
    node* param1;        /**<First child node */
    node* param2;        /**<Second child node */
    node* param3;        /**<Third child node */
};
typedef struct node* tree;

extern unordered_map<string,string> opTable;    /**<The table containing opcodes*/
extern string last_string;                      /**<Last identifier found */
extern deque<int> v;                            /**<Values for memlocs */
extern int pc;                                 /**<Program counter */
extern ofstream outfile;                        /**<Code output file */
extern ofstream reg_out;                        /**<Register output file */
extern ofstream mem_out;                        /**<Memory output file */
extern vector<string> words;                    /**<32-bit binary instructions */
extern unordered_map<string, int> symTable;     /**<The Symbol Table*/
extern tree SynTree;                            /**<The syntax tree generated by the parser*/

void initRegister(int r, int v);
void initMemloc(int l, int v);
void initMemlocs(int l, deque<int> v);
int find_symbol(string);
void insert_symbol(string,int);
tree make_node(string type, int value, node* p1, node* p2, node* p3);
void append_tree(node* node);
void visit_tree(node*);
void substitute(string f, string p1, string p2);
void load_optable();

