#!/bin/bash

usage(){
    echo "Usage: ./assembler -f file.drisc"
    exit
}

if [ "$#" -eq 0  -o "${2##*.}" != "drisc" ]; then
    usage
fi

while getopts ":f:" opt; do
  case ${opt} in
    f ) f=$OPTARG
      ;;
    \? ) usage
      ;;
  esac
done
shift $((OPTIND -1))

if [ -z "${f}" ]; then
    usage
fi


./pars ${f} < ${f}