#!/bin/bash

usage(){
    echo "Usage: ./interpreter -f file.o"
    exit
}

if [ "$#" -eq 0  -o "${2##*.}" != "o" ]; then
    usage
fi

while getopts ":f:" opt; do
  case ${opt} in
    f ) f=$OPTARG
      ;;
    \? ) usage
      ;;
  esac
done
shift $((OPTIND -1))

if [ -z "${f}" ]; then
    usage
fi

./int ${f}